#!/usr/bin/env bash

export CONTECO_LABEL="module.kafka_rest - ContEco"
export CONTECO_DESCRIPTION="Kafka REST module with managed standard URL."

export CONTECO_TYPE="module"
export CONTECO_NAME="kafka_rest"
export CONTECO_TAG="v1.0.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
